# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxx
    password: xxxx
    url: jdbc:mysql://localhost:3306/onepiece?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    druid:
      initialSize: 5                           # 初始连接数
      minIdle: 10                              # 最小连接池数量
      maxActive: 20                            # 最大连接池数量
      maxWait: 60000                           # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000       # 配置一个连接在池中最小生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000       # 配置一个连接在池中最大生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL      # 配置检测连接是否有效
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow:                                 # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: xxxxxxxxxxxxxx         # 控制台管理用户名和密码
        login-password: xxxxxxxxxxxxxx
      filter:
        stat:
          enabled: true
          log-slow-sql: true                   # 慢SQL记录
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true